### ISSUE TITLE
Could not build module when using cocoa pods with use_framework! mode

### ISSUE THREAD

**Issue by sbhhbs** [facebook/FBMemoryProfiler#1] opened 2016-04-14 03:59 UTC
Could not build module when using cocoa pods with use_framework! mode.
![2016-04-14 11 59 14](https://cloud.githubusercontent.com/assets/1070754/14516706/58843fe4-0238-11e6-9263-9bec971f40df.png)

**Comment by vijaytholpadi** [comment] 2016-04-14 04:51
+1

**Comment by Gricha** [comment] 2016-04-14 05:16
I was able to reproduce the issue on my machine as well. I will think more about better fix, but for now as a work around please change the files extensions you are using this for to be .mm instead of .m (Basically the projects underneath are using Objective-C++ and when using frameworks, it's not working as I'd expect)

**Comment by Gricha** [comment] 2016-04-14 05:33
I think the issue is that, since we do not define which headers are public in .podspec, CocoaPods uses all of them, pulling in C++ headers as well.

I'll fix it by manually providing proper headers to both FBRetainCycleDetector and FBAllocationTracker.

**Comment by knellr** [comment] 2016-04-14 11:50
The workaround caused more problems for me since modules are disabled with c++ and and we use @import via our pre-compiled header. I'll be waiting on a fix for this one :)

**Comment by Gricha** [comment] 2016-04-14 17:26
This should be resolved now as of version `0.1.1`. I updated specs in all depending repositories, please `pod update` and check if it is working for you. I will keep the issue open for a while to make sure everything is resolved.

**Comment by hhanesand** [comment] 2016-04-20 15:30
Working for me now with `use_frameworks!`

**Closed** 2016-04-20 20:45 UTC
Labels: bug
