### ISSUE TITLE
UI is missing buttons, allocations, generations

### ISSUE THREAD

**Issue by eliburke** [facebook/FBMemoryProfiler#10] opened 2016-04-21 16:00 UTC
I've followed your posted instructions: 
all 3 frameworks built via carthage, FBAllocationTrackerManager initialized in main(), and FBMemoryProfiler initialized in application:didFinishLaunchingWithOptions. 
I've turned off all of my appearance proxies and verified that my Large Text accessibility settings are off. I've tried on the simulator (6 and 6+) and on actual hardware (6S+). 

In all cases, the profiler UI comes up looking like this, with no entries, a truncated Mark Generations button, and missing buttons for Retain Cycles and Expand. The memory readout changes as I interact with the app, so some part of it is working correctly. 

Any ideas on what could be wrong?
![screen shot 2016-04-21 at 11 41 47 am](https://cloud.githubusercontent.com/assets/2371768/14715880/9db6b54e-07b8-11e6-95be-2184e49778b1.png)

**Comment by walkdianzi** [comment] 2016-04-22 09:45
I also have this problem, @Gricha Can you help us to solve it

**Comment by absolute-heike** [comment] 2016-04-22 11:57
This happens, because (at least for cocoapods) the DEBUG Macro is not set to 1, when compiling the pod code. You have to set it manually.

**Comment by walkdianzi** [comment] 2016-04-22 12:46
Yes, I know don't set DEBUG Macro to 1。In My target I set Debug like this image
![2016-04-22 8 39 46](https://cloud.githubusercontent.com/assets/5734867/14741706/bc548770-08ca-11e6-8c2a-4102fff75c83.png)

now I set Debug like this

![2016-04-22 8 38 42](https://cloud.githubusercontent.com/assets/5734867/14741765/3d42bad2-08cb-11e6-8c28-365011c3a496.png)

**Comment by absolute-heike** [comment] 2016-04-22 12:50
Alternatively you could also define these macros:
`'FB_MEMORY_TOOLS=1', 'RETAIN_CYCLE_DETECTOR_ENABLED=1', 'ALLOCATION_TRACKER_ENABLED=1' `

**Comment by eliburke** [comment] 2016-04-22 17:36
I updated to 0.1.2 and tried defining all of these variables. I made sure to run carthage with "--configuration Debug". The only difference is that my "Ma...en." button now reads "Mark Gen." There is still no list of classes, retain/expand button, etc. Has anyone else successfully used the Carthage-built version?

![screen shot 2016-04-22 at 1 34 46 pm](https://cloud.githubusercontent.com/assets/2371768/14749689/04b95144-088f-11e6-8f61-eedea2b8f74c.png)

**Comment by Gricha** [comment] 2016-04-25 16:40
My understanding is this happens when you use Carthage, is that correct?

I'll test it later today and will try to come up with solution if I can repro it.

**Comment by Gricha** [comment] 2016-04-25 16:59
Yeah, this is reproducible under Carthage, my bet now is that we bootstrap libraries from releases for both allocation tracker and retain cycle detector, and they are built with wrong flags, I'll look into that

**Comment by Gricha** [comment] 2016-04-25 17:14
Temporary workaround - when you update your Carthage checkout, please pass flag `--no-use-binaries`

The reason for the bug is that we have prebuilt binaries in Release configuration and Carthage will always pick them. I am not sure if I can provide both configurations over there, or just remove releases.

**Comment by ppaulojr** [comment] 2016-04-25 19:49
I'm having the same problem but no button is displayed.

**Comment by Gricha** [comment] 2016-04-25 21:26
@ppaulojr can you share how you enabled memory profiler (code snippet)? Can you try with --no-use-binaries in Carthage?

**Comment by ppaulojr** [comment] 2016-04-25 21:29
I use Cocoapods and I used exactly the same code from the README

------------------------------
Pedro Paulo Junior



On Mon, Apr 25, 2016 at 6:27 PM, Grzegorz Pstrucha <notifications@github.com

**Comment by Gricha** [comment] 2016-04-25 21:53
@ppaulojr I'd probably still need to see some code/configurations. Or small project that reproes it. Without that it's really hard to move it. I'll close this issue, since it's Carthage specific, but feel free to open another one for your problem.

For the issue with Carthage, for now I removed prebuilt binaries, forcing redownload should be enough to fix the issue

**Closed by Gricha** 2016-04-25 21:53 UTC

**Comment by eikebartels** [comment] 2016-04-27 11:51
I had the same issue. The problem was, that my build configuration is different for different schemas. To get it running I had to specify DEBUG=1 for the pod itself. 

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DEBUG=1']
            end
    end
end
```
